name = "signos-stt-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[ai]
binding = "AI"
remote = true  # AI bindings always use remote resources

[[vectorize]]
binding = "VECTORIZE"
index_name = "signos-lsch-index"
remote = true  # Required for local dev - Vectorize doesn't support local mode

# Environment variables (set these via wrangler secret put or dashboard)
# Set MOCK_MODE via: wrangler secret put MOCK_MODE
# For dev, use .dev.vars file
[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

# Optional: KV namespace for session storage (future use)
# [[kv_namespaces]]
# binding = "SESSION_STORE"
# id = "YOUR_KV_NAMESPACE_ID"
# preview_id = "YOUR_PREVIEW_KV_ID"