name = "signos-agentic-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# AI binding for conversational agent
[ai]
binding = "AI"

# Vectorize binding for sign lookup
[[vectorize]]
binding = "VECTORIZE"
index_name = "signos-lsch-index"

# Knowledge Vectorize binding for educational content
[[vectorize]]
binding = "KNOWLEDGE_VECTORIZE"
index_name = "signos-knowledge-index"

# D1 database for user progress
[[d1_databases]]
binding = "DB"
database_name = "signos-agentic-db"
database_id = "b26a466b-5cbf-4be1-b484-df3e55ba59b3" 

# KV for session management
[[kv_namespaces]]
binding = "SESSIONS"
id = "8bc28ee8b0d142459c9a9c887efe6a08" 

# Development configuration
[dev]
# Local development uses local D1 database by default

